### ISSUE TITLE
how to using

### ISSUE THREAD

**Issue by NCLnclNCL** [vytautassurvila/vscode-csharp-ls#1]
i can easy using this extension https://github.com/statiolake/vscode-csharp-ls but your extension is not working

**Comment by vytautassurvila** [comment]
@NCLnclNCL could you please clarify what exactly does not work?

How to build and install extension:
https://github.com/vytautassurvila/vscode-csharp-ls/blob/2b7253207a297304ae38b3ad6977e5b8900158cc/README.md?plain=1#L13

If you managed to install it but it doesn't work in vscode then could you please provide full logs from vscode "Output" -> "Extension Host" and "Output" -> "CSharp Language Server"?

**Comment by NCLnclNCL** [comment]
> @NCLnclNCL could you please clarify what exactly does not work?
> 
> How to build and install extension:
> 
> https://github.com/vytautassurvila/vscode-csharp-ls/blob/2b7253207a297304ae38b3ad6977e5b8900158cc/README.md?plain=1#L13
> 
> If you managed to install it but it doesn't work in vscode then could you please provide full logs from vscode "Output" -> "Extension Host" and "Output" -> "CSharp Language Server"?

I think you should edit this extension so that it can choose external lsp instead of having to install lsp from nuget, I have built and imported but no output, maybe because I'm using dotnet8 and that nuget package uses dotnet7 so it doesn't work

**Comment by vytautassurvila** [comment]
> I think you should edit this extension so that it can choose external lsp instead of having to install lsp from nuget, I have built and imported but no output, maybe because I'm using dotnet8 and that nuget package uses dotnet7 so it doesn't work

You could try set `csharp-ls.dev.local-nupkg-dir`: https://github.com/vytautassurvila/vscode-csharp-ls/blob/2b7253207a297304ae38b3ad6977e5b8900158cc/README.md?plain=1#L21
Then it would install csharp-ls from your local directory (the one you used to build csharp-ls).
https://github.com/vytautassurvila/vscode-csharp-ls/blob/2f4e37e5552e8f286eab4187bb09921f6b054e2f/src/cSharpLsServer.ts#L37-L42

Keep in mind that csharp-ls version and this https://github.com/vytautassurvila/vscode-csharp-ls/blob/2b7253207a297304ae38b3ad6977e5b8900158cc/src/constants/csharpLsVersion.ts#L1 should match in order `csharp-ls.dev.local-nupkg-dir` would work.

And probably extension could improved to ignore csharp-ls version at all if `csharp-ls.dev.local-nupkg-dir` is set. Then development would be less confusing

**Comment by NCLnclNCL** [comment]
> > I think you should edit this extension so that it can choose external lsp instead of having to install lsp from nuget, I have built and imported but no output, maybe because I'm using dotnet8 and that nuget package uses dotnet7 so it doesn't work
> 
> You could try set `csharp-ls.dev.local-nupkg-dir`:
> 
> https://github.com/vytautassurvila/vscode-csharp-ls/blob/2b7253207a297304ae38b3ad6977e5b8900158cc/README.md?plain=1#L21
> 
> 
> Then it would install csharp-ls from your local directory (the one you used to build csharp-ls).
> https://github.com/vytautassurvila/vscode-csharp-ls/blob/2f4e37e5552e8f286eab4187bb09921f6b054e2f/src/cSharpLsServer.ts#L37-L42
> 
> Keep in mind that csharp-ls version and this
> 
> https://github.com/vytautassurvila/vscode-csharp-ls/blob/2b7253207a297304ae38b3ad6977e5b8900158cc/src/constants/csharpLsVersion.ts#L1
> 
> should match in order `csharp-ls.dev.local-nupkg-dir` would work.
> And probably extension could improved to ignore csharp-ls version at all if `csharp-ls.dev.local-nupkg-dir` is set. Then development would be less confusing

Oh how to it check version bro, lsp only is a app, and my lsp is unpacked

**Comment by NCLnclNCL** [comment]
> > I think you should edit this extension so that it can choose external lsp instead of having to install lsp from nuget, I have built and imported but no output, maybe because I'm using dotnet8 and that nuget package uses dotnet7 so it doesn't work
> 
> You could try set `csharp-ls.dev.local-nupkg-dir`:
> 
> https://github.com/vytautassurvila/vscode-csharp-ls/blob/2b7253207a297304ae38b3ad6977e5b8900158cc/README.md?plain=1#L21
> 
> 
> Then it would install csharp-ls from your local directory (the one you used to build csharp-ls).
> https://github.com/vytautassurvila/vscode-csharp-ls/blob/2f4e37e5552e8f286eab4187bb09921f6b054e2f/src/cSharpLsServer.ts#L37-L42
> 
> Keep in mind that csharp-ls version and this
> 
> https://github.com/vytautassurvila/vscode-csharp-ls/blob/2b7253207a297304ae38b3ad6977e5b8900158cc/src/constants/csharpLsVersion.ts#L1
> 
> should match in order `csharp-ls.dev.local-nupkg-dir` would work.
> And probably extension could improved to ignore csharp-ls version at all if `csharp-ls.dev.local-nupkg-dir` is set. Then development would be less confusing

Not working, i need wait update as that extension with .exe

**Comment by vytautassurvila** [comment]
Now you can specify executable path in settings. If you use windows then something like `"csharp-ls.dev.csharp-ls-executable": "C:\YOUR_PATH\CSharpLanguageServer.exe` should work

**Comment by vytautassurvila** [comment]
With last release the setting for csharp-ls executable was renamed to `csharp-ls.csharp-ls-executable`. For linux the path could be `dotnet /home/user/.../Debug/net7.0/CSharpLanguageServer.dll`, for windows (have not tested myself) `C:\YOUR_PATH\CSharpLanguageServer.exe` and if you wan't to try other csharp-ls versions installed globally from nugget `dotnet tool install --global csharp-ls` then the value should be `csharp-ls`.

Please reopen the ticket if it still doesn't work for you
