### ISSUE TITLE
how to disable this

### ISSUE THREAD

**Issue by NCLnclNCL** [vytautassurvila/vscode-csharp-ls#2]
i want disable IntelliSense parameter documentation as value:
https://imgur.com/a/wtHWPa8

**Comment by vytautassurvila** [comment]
I'm unable to reproduce that. @NCLnclNCL are you sure it's not caused by some other extension?

**Comment by vytautassurvila** [comment]
In you vscode settings disable inlay hints `"editor.inlayHints.enabled": "off"`
