### ISSUE TITLE
Load the solution too frequently

### ISSUE THREAD

**Issue by crepassob** [vytautassurvila/vscode-csharp-ls#3]
First,Thanks you create this plug-in and I like it.

When I use Nuget to add package,the solution will be reloading.This problem caused by file updates caused by adding Itemgroup to .csproj.I think is too frequently.
In my another project about Unity.Because unity adds all code-related files to the ItemGroup snippet in .csproj,this cause the solution will keey reloading.It was a terrible experience.

I think the plug-in loads everything in the solution at startup and only loads the changes when the file is updated.
(My English not particularly good.If there is something you don`t understand,you can ask again.)

**Comment by vytautassurvila** [comment]
This extension uses  [csharp-language-server](https://github.com/razzmatazz/csharp-language-server) and it uses [Roslyn](https://github.com/dotnet/roslyn) to parse code. At the moment Roslyn does not support reload of single project https://github.com/dotnet/roslyn/issues/7842. Therefore when new package is added or any other change is done on csproj file the whole solution is reloaded.

> In my another project about Unity.Because unity adds all code-related files to the ItemGroup snippet in .csproj,this cause the solution will keey reloading.It was a terrible experience.

I'm not familiar with Unity development. Could you give me an example what change in .csproj file should not trigger solution reload (in other words what .csproj change does not affect it's .cs files)?

> I think the plug-in loads everything in the solution at startup and only loads the changes when the file is updated.

This way it works for all .cs files - they are loaded on startup and on each save only single .cs file is reloaded. But as soon as you save .csproj or .sln file then whole solution will be reloaded

**Comment by crepassob** [comment]
> I'm not familiar with Unity development. Could you give me an example what change in .csproj file should not trigger solution reload (in other words what .csproj change does not affect it's .cs files)?

For example,When I add this document `test.shader` in Unity.and then the Unity will add this
``` xml
<ItemGroup>
    <None Include="Assets\shader\test.shader" />
</ItemGroup>
```
in .csproj file.

If I create a new .cs in Unity,and then the Unity will add this

```xml
<ItemGroup>
    <Compile Include="Assets\shader\test.cs" />
</ItemGroup>

```
in .csproj file.

I tried delect ` <Compile Include="Assets\shader\test.cs" />`,but doing so will cause LSP to have no effect on this file.
So I think this problem should not be solved easily 🫤.And I review this [https://github.com/dotnet/roslyn/issues/7842](url) issuse.It seems nobody care this.

I think add the .csproj buffer file to fix this  `<None Include="Assets\shader\test.shader" />` situation.If the plug-in match to this lable.The .csproj will not to be passed to LSP.At least this will not prevent the plug-in from loading too frequently in Unity.

**Comment by crepassob** [comment]
Here is a complete .csproj file that I hope can give you some help
[Assembly-CSharp.csproj.txt](https://github.com/vytautassurvila/vscode-csharp-ls/files/13487334/Assembly-CSharp.csproj.txt)

**Comment by vytautassurvila** [comment]
Looks like Unity uses NET Framework. Accordingly it uses old csproj format that you have to add every file with `<Compile .../>`. I see how it might trigger lots of solution reloads.

Sadly I don't see easy fix here. All heavy lifting is done by csharp-language-server. It also itself monitors files for changes - including csproj. And at the moment it can only receive what file was changed and type of change (file created, edited, removed). It does not know what lines were actually changed. 
https://github.com/razzmatazz/csharp-language-server/blob/8bc48b941b9b211f4c82f2fe6afc0f92a8bc635e/src/CSharpLanguageServer/Server.fs#L1524-L1528

If you are willing to attempt to submit pull request then this issue probably could be moved to https://github.com/razzmatazz/csharp-language-server. Maybe someone will suggest ideas how to prevent solution reloads.

**Comment by crepassob** [comment]
Thanks your answer and I have understood the specific problem.Since this problem is caused by [csharp](https://github.com/razzmatazz/csharp-language-server) and the entire load is provided by it.I will hand over the issues later and close this issues.
